# Собираем фронтенд
FROM node:18 AS build
WORKDIR /app

# Копируем зависимости и конфигурации
COPY ./frontend/package*.json ./frontend/.babelrc ./

# Устанавливаем зависимости
RUN npm install
RUN npm install react-router-dom

# Копируем исходники
COPY ./frontend .

# Собираем проект
RUN npm run build

# Запускаем веб-сервер
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
