# Собираем фронтенд
FROM node:18 AS build
WORKDIR /app

# Копируем зависимости и конфигурации
COPY ./frontend/package*.json ./frontend/.babelrc ./

# Устанавливаем зависимости
RUN npm create vite@latest bookstore-frontend --template react
CMD cd bookstore-frontend
RUN npm install

RUN npm install --save-dev \
      tailwindcss \
      postcss \
      autoprefixer \
      style-loader \
      css-loader \
      webpack \
      webpack-cli \
      babel-loader \
      @babel/core \
      @babel/preset-env \
      @babel/preset-react \
      react-router-dom
#RUN npx tailwindcss init -p

# Копируем исходники
COPY ./frontend .

# Собираем проект
RUN npm run build

# Запускаем веб-сервер
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
