version: '3.8'

services:
  backend:
    build: ./backend
    container_name: bookstore-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:bookstore
      - SPRING_H2_CONSOLE_ENABLED=true
    networks:
      - bookstore-network

  frontend:
    build: ./frontend
    container_name: bookstore-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - bookstore-network
  postgres:
    image: postgres:15-alpine
    container_name: bookstore_postgres
    environment:
      POSTGRES_DB: bookstore_db
      POSTGRES_USER: bookstore_user
      POSTGRES_PASSWORD: Awdxzqetgvcfr
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/src/main/resources/db/migration:/docker-entrypoint-initdb.d

networks:
  bookstore-network:
    driver: bridge

volumes:
  postgres_data: