# Stage 1: Сборка
FROM maven:3.8.5-openjdk-17 AS build
WORKDIR /app

# Копируем только необходимые файлы
COPY pom.xml .
COPY backend/src backend/src
#COPY backend/src/main/java backend/src/main/java
#COPY backend/src/main/resources backend/src/main/resources


RUN ls -la /app

# Собираем проект внутри контейнера
RUN mvn clean package -DskipTests

# Stage 2: Финальный образ
FROM openjdk:17-jdk-slim

WORKDIR /app

# Копируем JAR из стадии сборки
COPY --from=build /app/target/bookstore-0.0.1-SNAPSHOT.jar app.jar

# Копируем wait-for-it.sh и entrypoint.sh
COPY backend/wait-for-it.sh /app/wait-for-it.sh
COPY backend/entrypoint.sh /app/entrypoint.sh

# Делаем скрипт исполняемым
RUN chmod +x /app/wait-for-it.sh /app/entrypoint.sh && \
    apt-get update && \
    apt-get install -y netcat && \
    rm -rf /var/lib/apt/lists/*

EXPOSE 8080
ENTRYPOINT ["/app/entrypoint.sh"]
#CMD ["sh", "-c", "java -jar app.jar || sleep infinity"]
#ENTRYPOINT ["java", "-jar", "app.jar"]