spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Docker-??????????? ?????????
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:bookstore}
spring.h2.console.enabled=${SPRING_H2_CONSOLE_ENABLED:true}
spring.h2.console.path=/h2-console

# ????????? ??? ?????? ?? ??????
server.forward-headers-strategy=framework